
service: 1122
provider:
  name: aws
  stage: dev
  runtime: nodejs10.x
  environment:
    DB_HOST: host.com
    DB_PORT: 3306
    DB_NAME: mydb
    DB_USERNAME: quyencm
    DB_PASSWORD: password

functions:
  
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: graphqlServer.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
  
    